import { pageImagery } from '@/lib/imagery';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Check, ArrowUpRight } from 'lucide-react';
import { services, site } from '@/lib/site';
import { PageHero, CTA, ProcessSteps, Eyebrow, Photo, Button, TrustBar } from '@/components/ui';
import { WhyUs, Weather, Services, Warranty } from '@/components/home-sections';
import { ProjectGallery, Materials } from '@/components/gallery';
import ServiceArea from '@/components/service-area';
import Reviews from '@/components/reviews';
import ContactForm from '@/components/contact-form';
import FAQ from '@/components/faq';

const pages:Record<string,{title:string;copy:string;eyebrow:string}> = {
  about:{title:'A thoughtful approach. A roof to feel good about.',copy:'Homes are personal. Roofing should start with listening, a clear plan, and care for the details that matter to you.',eyebrow:'ABOUT OUR APPROACH'},
  'roofing-services':{title:'Complete care for the roof over your head.',copy:'Roof repairs, replacements, inspections, and more. Explore residential roofing solutions for Portland homes.',eyebrow:'RESIDENTIAL ROOFING SERVICES'},
  projects:{title:'Every roof has a story.',copy:'A place to explore rooflines, materials, and the details behind a well-considered home.',eyebrow:'SAMPLE ROOFING PROJECTS'},
  'service-areas':{title:'Proudly serving Portland & surrounding communities.',copy:'Start with your neighborhood. Explore the region and ask about your property.',eyebrow:'LOCAL ROOTS. LOCAL HOMES.'},
  reviews:{title:'A place for homeowner perspectives.',copy:'Explore sample testimonials illustrating the experience we aim to provide. These examples are fictional.',eyebrow:'HOMEOWNER REVIEWS'},
  contact:{title:'A better roof starts with a conversation.',copy:'Tell us about your home, ask a question, or request your free roofing estimate.',eyebrow:'LET’S GET STARTED'},
  'privacy-policy':{title:'Your privacy matters.',copy:'How your contact information is used when you request an estimate.',eyebrow:'PRIVACY POLICY'},
  'terms-of-service':{title:'Clear expectations from the start.',copy:'Information about using this website and requesting roofing services.',eyebrow:'TERMS OF SERVICE'},
};

export function generateStaticParams(){return [...Object.keys(pages),...services.map(s=>s.slug)].map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const service=services.find(s=>s.slug===slug);const page=pages[slug];if(!page&&!service)return{};return{title:service?`${service.name} in Portland, Oregon`:page.title,description:service?.description||page.copy,...(site.url?{alternates:{canonical:`/${slug}`}}:{})};}

export default async function Page({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params;
  const service=services.find(s=>s.slug===slug);
  if(service){
    const defaultService=service.name==='New Roof Installation'?'New Roof':service.name==='Storm Damage Repair'?'Storm Damage':service.name;
    return <><PageHero eyebrow={`PORTLAND RESIDENTIAL ROOFING / ${service.name.toUpperCase()}`} title={`${service.name}. ${service.short}`} copy={service.description} image={service.image} imageAlt={service.imageAlt}/><TrustBar/><section className="section"><div className="container service-overview"><div><Eyebrow>A CLOSER LOOK AT YOUR ROOF</Eyebrow><h2>{service.name} for Portland homes.</h2><p>{service.approach}</p><h3>When it’s time to take a closer look</h3><ul className="check-list">{service.problems.map(problem=><li key={problem}><Check size={18}/>{problem}</li>)}</ul><Button>Request a roof assessment</Button></div><Photo src={service.overviewImage} alt={service.overviewAlt}/></div></section><section className="service-benefits"><div className="container"><Eyebrow>OUR APPROACH</Eyebrow><h2>A clear plan. Thoughtful work.</h2><div className="benefit-grid">{service.benefits.map((benefit,i)=><article key={benefit}><span>0{i+1}</span><h3>{benefit}</h3><p>{['Start with the condition of your home and an honest conversation about your priorities.','Review the recommended scope, material options, and any questions before moving ahead.','Understand the next steps and the maintenance considerations for your roofing system.'][i]}</p></article>)}</div></div></section><ProcessSteps/><ProjectGallery/><FAQ all/><CTA/><ContactForm defaultService={defaultService}/><div className="container related-services"><h3>Explore other roofing services</h3>{services.filter(s=>s.slug!==slug).map(s=><Link key={s.slug} href={`/${s.slug}`}>{s.name}<ArrowUpRight size={15}/></Link>)}</div></>;
  }
  const page=pages[slug];if(!page)notFound();
  if(slug==='privacy-policy'||slug==='terms-of-service')return <><PageHero {...page} cta={false}/><section className="section"><div className="container legal-content">{slug==='privacy-policy'?<><h2>Information you provide</h2><p>Our estimate form collects your name, phone number, email, property address, project type, timeline, and any project details you choose to include. Please do not include sensitive financial information.</p><h2>How inquiries are delivered</h2><p>When you submit the form, we send your inquiry to our business inbox using Resend, our email delivery provider. We use these details to respond, discuss your project, and arrange follow-up. Your email address is included as the reply-to address.</p><h2>Storage and website services</h2><p>This website does not maintain a separate customer database. Inquiries are processed by our email delivery provider and stored in our business mailbox. Our hosting and email providers may process technical logs to operate and protect their services. This website does not use advertising trackers or analytics cookies.</p><h2>Questions and requests</h2><p>Contact <a href={site.emailHref}>{site.email}</a> to ask about your information or request a correction or deletion. We will review your request and explain any records that need to be retained for an ongoing project or applicable obligations.</p></>:<><h2>Using this website</h2><p>This site describes residential roofing services and helps you contact {site.name}. Information about materials and projects is general; suitability and availability depend on your property and the agreed scope.</p><h2>Estimate inquiries</h2><p>Sending an inquiry does not schedule work or create a roofing contract. We will discuss your needs and next steps. Project scope, price, schedule, and any fees must be agreed before work begins.</p><h2>Sample content</h2><p>Reviews labeled as samples are fictional, not customer endorsements. Sample projects and illustrative photographs do not represent completed company work. Example schedules are illustrative and do not guarantee a completion date.</p><h2>Project agreements and warranties</h2><p>Your written agreement sets out the work and applicable terms. Ask about manufacturer and workmanship coverage, including eligibility, exclusions, and maintenance requirements, before choosing a roofing system.</p><h2>Contact us</h2><p>{site.name} · <a href={site.phoneHref}>{site.phone}</a> · <a href={site.emailHref}>{site.email}</a> · {site.address}</p></>}<Button href="/contact" variant="button-outline">Contact information</Button></div></section></>;
  return <><PageHero {...page} image={pageImagery[slug]?.src} imageAlt={pageImagery[slug]?.alt} cta={slug!=='contact'}/>{slug==='about'&&<><section className="section about-story"><div className="container"><Eyebrow>THE PEOPLE BEHIND THE WORK</Eyebrow><h2>Local roots. A personal conversation.</h2><p>Platinum Exteriors, Inc. is your starting point for a thoughtful roofing conversation in Canby and the Portland region. Connect with owner Keeton Epps to discuss your home, the condition of your roof, and what you want to achieve.</p><p>Our approach starts with listening. Whether you are exploring repairs, a replacement, or a roof for a new home, the priorities are clear: understand the property, discuss practical options, and agree on the details before work begins.</p><p>A well-planned project considers the whole roof, from materials and flashing to ventilation and drainage. We want you to understand the proposed work and feel comfortable asking questions along the way.</p></div></section><WhyUs/><Weather/><Warranty/></>}{slug==='roofing-services'&&<><Services full/><Materials/><ProcessSteps/></>}{slug==='projects'&&<ProjectGallery full/>}{slug==='service-areas'&&<ServiceArea/>}{slug==='reviews'&&<Reviews full/>}{slug==='contact'?<ContactForm/>:<CTA/>}{['contact','roofing-services'].includes(slug)&&<FAQ all/>}</>;
}
