import { pageImagery } from '@/lib/imagery';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Check, ArrowUpRight } from 'lucide-react';
import { services, site } from '@/lib/site';
import { PageHero, CTA, ProcessSteps, Eyebrow, Photo, Button, TrustBar } from '@/components/ui';
import { WhyUs, Weather, Services, Warranty } from '@/components/home-sections';
import { ProjectGallery, Materials } from '@/components/gallery';
import ServiceArea from '@/components/service-area';
import Reviews from '@/components/reviews';
import ContactForm from '@/components/contact-form';
import FAQ from '@/components/faq';

const pages:Record<string,{title:string;copy:string;eyebrow:string}> = {
  about:{title:'A thoughtful approach. A roof to feel good about.',copy:'Homes are personal. Roofing should start with listening, a clear plan, and care for the details that matter to you.',eyebrow:'ABOUT OUR APPROACH'},
  'roofing-services':{title:'Complete care for the roof over your head.',copy:'Roof repairs, replacements, inspections, and more. Explore residential roofing solutions for Portland homes.',eyebrow:'RESIDENTIAL ROOFING SERVICES'},
  projects:{title:'Every roof has a story.',copy:'A place to explore rooflines, materials, and the details behind a well-considered home.',eyebrow:'RECENT ROOFING PROJECTS'},
  'service-areas':{title:'Proudly serving Portland & surrounding communities.',copy:'Start with your neighborhood. Explore our proposed service area and ask about your property.',eyebrow:'LOCAL ROOTS. LOCAL HOMES.'},
  reviews:{title:'What Portland homeowners are saying.',copy:'Real experiences matter. This space is reserved for authentic customer reviews when they are available.',eyebrow:'HOMEOWNER REVIEWS'},
  contact:{title:'A better roof starts with a conversation.',copy:'Tell us about your home, ask a question, or request your free roofing estimate.',eyebrow:'LET’S GET STARTED'},
  'privacy-policy':{title:'Your privacy matters.',copy:'A clear view of how the estimate inquiry form works in this website preview.',eyebrow:'PRIVACY POLICY · DRAFT'},
  'terms-of-service':{title:'Clear expectations from the start.',copy:'Website preview information and proposed terms, pending business review.',eyebrow:'TERMS OF SERVICE · DRAFT'},
};

export function generateStaticParams(){return [...Object.keys(pages),...services.map(s=>s.slug)].map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const service=services.find(s=>s.slug===slug);const page=pages[slug];if(!page&&!service)return{};return{title:service?`${service.name} in Portland, Oregon`:page.title,description:service?.description||page.copy,...(process.env.NEXT_PUBLIC_SITE_URL?{alternates:{canonical:`/${slug}`}}:{})};}

export default async function Page({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params;
  const deliveryEnabled=!!process.env.ESTIMATE_WEBHOOK_URL;
  const service=services.find(s=>s.slug===slug);
  if(service){
    const defaultService=service.name==='New Roof Installation'?'New Roof':service.name==='Storm Damage Repair'?'Storm Damage':service.name;
    return <><PageHero eyebrow={`PORTLAND RESIDENTIAL ROOFING / ${service.name.toUpperCase()}`} title={`${service.name}. ${service.short}`} copy={service.description} image={service.image} imageAlt={service.imageAlt}/><TrustBar/><section className="section"><div className="container service-overview"><div><Eyebrow>A CLOSER LOOK AT YOUR ROOF</Eyebrow><h2>{service.name} for Portland homes.</h2><p>{service.approach}</p><h3>When it’s time to take a closer look</h3><ul className="check-list">{service.problems.map(problem=><li key={problem}><Check size={18}/>{problem}</li>)}</ul><Button>Request a roof assessment</Button></div><Photo src={service.overviewImage} alt={service.overviewAlt}/></div></section><section className="service-benefits"><div className="container"><Eyebrow>OUR APPROACH</Eyebrow><h2>A clear plan. Thoughtful work.</h2><div className="benefit-grid">{service.benefits.map((benefit,i)=><article key={benefit}><span>0{i+1}</span><h3>{benefit}</h3><p>{['Start with the condition of your home and an honest conversation about your priorities.','Review the recommended scope, material options, and any questions before moving ahead.','Understand the next steps and the maintenance considerations for your roofing system.'][i]}</p></article>)}</div></div></section><ProcessSteps/><ProjectGallery/><FAQ all/><CTA/><ContactForm deliveryEnabled={deliveryEnabled} defaultService={defaultService}/><div className="container related-services"><h3>Explore other roofing services</h3>{services.filter(s=>s.slug!==slug).map(s=><Link key={s.slug} href={`/${s.slug}`}>{s.name}<ArrowUpRight size={15}/></Link>)}</div></>;
  }
  const page=pages[slug];if(!page)notFound();
  if(slug==='privacy-policy'||slug==='terms-of-service')return <><PageHero {...page} cta={false}/><section className="section"><div className="container legal-content"><div className="preview-notice">Draft website information. The business owner must complete and approve the applicable policy before publication.</div>{slug==='privacy-policy'?<><h2>Information you provide</h2><p>The estimate form asks for your name, contact details, property location, and project information. Avoid including financial information or other sensitive details.</p><h2>How this preview works</h2><p>When the form displays “Website preview,” your completed inquiry stays in the current page memory and is not submitted to the company. You may download a copy to your device. Reloading or leaving the page clears the draft.</p><h2>When inquiry delivery is enabled</h2><p>Submitting a request sends the form information to a configured inquiry provider so the company can respond. Provider identity, access controls, retention periods, and contact procedures must be completed by the business before launch.</p><h2>Cookies and analytics</h2><p>This implementation does not include advertising trackers or an analytics integration. Hosting infrastructure may process standard request logs; the final policy should describe the chosen hosting provider.</p><h2>Your questions</h2><p>[PRIVACY CONTACT EMAIL] · {site.name} · [RETENTION AND DELETION PROCEDURE]</p></>:<><h2>About this website</h2><p>This preview describes proposed residential roofing services for the Portland market. Business details, service availability, materials, credentials, and project examples remain subject to owner confirmation.</p><h2>Estimate inquiries</h2><p>An inquiry does not schedule work or create a roofing contract. Final scope, pricing, materials, timing, and any applicable coverage should be set out in a separate written agreement.</p><h2>Illustrative content</h2><p>Concept imagery and reference photographs do not represent completed company projects. Review placeholders do not represent customer statements or ratings.</p><h2>Service and warranty terms</h2><p>{site.name} · [SERVICE AGREEMENT TERMS] · [APPLICABLE WARRANTY TERMS] · [BUSINESS CONTACT DETAILS]</p><h2>Final terms</h2><p>Business-specific terms and applicable provisions must be supplied and reviewed before this draft is published as the company’s terms of service.</p></>}<Button href="/contact" variant="button-outline">Contact information</Button></div></section></>;
  return <><PageHero {...page} image={pageImagery[slug]?.src} imageAlt={pageImagery[slug]?.alt} cta={slug!=='contact'}/>{slug==='about'&&<><section className="section about-story"><div className="container"><Eyebrow>THE PEOPLE BEHIND THE WORK</Eyebrow><h2>A local story, ready to be told.</h2><p>[COMPANY STORY, OWNERSHIP, AND TEAM DETAILS]</p><p>This space is reserved for the company’s real story: who you are, why you do this work, and what homeowners can expect. Verified experience and team photographs will be added when provided.</p></div></section><WhyUs/><Weather/><Warranty/></>}{slug==='roofing-services'&&<><Services full/><Materials/><ProcessSteps/></>}{slug==='projects'&&<ProjectGallery full/>}{slug==='service-areas'&&<ServiceArea/>}{slug==='reviews'&&<Reviews full/>}{slug==='contact'?<ContactForm deliveryEnabled={deliveryEnabled}/>:<CTA/>}{['contact','roofing-services'].includes(slug)&&<FAQ all/>}</>;
}
