'use client';
import { useRef, useState } from 'react';
import { ArrowUpRight, X } from 'lucide-react';
import { projects, materials } from '@/lib/site';
import { Button, Photo, SectionHeading } from './ui';

export function ProjectGallery({ full = false }: { full?: boolean }) {
  const [filter, setFilter] = useState('All projects');
  const [selected, setSelected] = useState<typeof projects[number] | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const displayed = (full ? projects : projects.slice(0,3)).filter(p=>filter==='All projects'||p.type===filter);
  return <section className="section projects-section"><div className="container"><SectionHeading eyebrow="A CLOSER LOOK" title="Explore the possibilities." copy="A sense of the homes, rooflines, and details that inspire our approach.">{!full && <Button href="/projects" variant="button-outline">View all projects</Button>}</SectionHeading><div className="gallery-notice"><span className="mini-label">SAMPLE PROJECTS</span><p>Fictional project examples with illustrative photography, showing possible scopes and materials.</p></div>{full && <div className="filters" aria-label="Filter projects">{['All projects','Roof Replacement','Roof Repair','New Roof Installation'].map(item=><button className={filter===item?'selected':''} onClick={()=>setFilter(item)} aria-pressed={filter===item} key={item}>{item}</button>)}</div>}<div className={`project-grid ${full?'project-grid-full':''}`}>{displayed.map((project,i)=><button className="project-card" key={project.id} onClick={()=>{setSelected(project);dialog.current?.showModal();}}><div className="project-photo"><Photo src={project.image} alt={project.alt}/><span className="project-chip">Sample project</span><span className="project-open"><ArrowUpRight size={22}/></span></div><div className="project-caption"><span>0{project.id} / {project.type}</span><h3>{project.name}</h3><p>{project.location} <span>↗</span></p></div></button>)}</div></div><dialog className="project-dialog" aria-labelledby="project-dialog-title" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button className="dialog-close" onClick={()=>dialog.current?.close()} aria-label="Close project"><X/></button>{selected && <><Photo src={selected.image} alt={selected.alt}/><div className="dialog-content"><span className="mini-label">FICTIONAL PROJECT EXAMPLE</span><h2 id="project-dialog-title">{selected.name}</h2><p>{selected.type} · {selected.material}</p><p>{selected.location} &middot; {selected.duration}</p><p>{selected.description}</p><h3>Example scope</h3><ul className="check-list">{selected.scope.map(item=><li key={item}>{item}</li>)}</ul><Button>Discuss a similar project</Button></div></>}</dialog></section>;
}

export function Materials() {
  const [active,setActive]=useState<number|null>(null);
  return <section className="section materials-section"><div className="container"><SectionHeading eyebrow="THE RIGHT ROOF FOR YOUR HOME" title="Considered materials. Lasting character." copy="Explore roofing possibilities, from familiar textures to clean, modern lines."/><p className="small-note material-note">Discuss material suitability, product availability, and warranty terms during your estimate.</p><div className="materials-grid">{materials.map((material,i)=><article key={material.name}><Photo src={material.image} alt={material.imageAlt} sizes="(max-width: 700px) 100vw, 33vw"/><h3>{material.name}</h3><p>{material.description}</p><button className="text-link" aria-expanded={active===i} aria-controls={`material-${i}`} onClick={()=>setActive(active===i?null:i)}>{active===i?'Show less':'What to consider'}<ArrowUpRight size={16}/></button><p className="material-details" id={`material-${i}`} hidden={active!==i}>{material.details}</p></article>)}</div></div></section>;
}
